Numpy - Numerical Python

In [2]:
# convert list to numpy array

import numpy as np

a = [8,6,2,4,7,3]
a = np.asarray(a)

print(a)
type(a)

[8 6 2 4 7 3]


numpy.ndarray

In [3]:
# convert set to numpy array

import numpy as np

a = {2,8,6,3,8,9,10}
a = np.asarray(a)

print(a)
type(a)

{2, 3, 6, 8, 9, 10}


numpy.ndarray

In [6]:
# creating numpy array

x = np.array([10,20,53,6,52,51,7,5,2])

print(x)
print(x[2])
x[2] = 26 # replace a value
print(x)
type(x)

[10 20 53  6 52 51  7  5  2]
53
[10 20 26  6 52 51  7  5  2]


numpy.ndarray

In [7]:
# get multiple row and column

y = np.array([[1,2,3,4],[5,6,7,8]])
print(y)
type(y)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [9]:
# shape of the array

y = np.array([[1,2,3],[5,6,7]])
print(y.shape)

(2, 3)


In [11]:
# create a null matrix

null = np.zeros((2,5))
print(null)
print(null.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)


In [14]:
# identity matrix

identity = np.eye(4,4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# array of all elements as 1

one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# array with an constant element

constant = np.full((3,4),8)
print(constant)
print(constant.shape)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
(3, 4)


In [24]:
# create an array with random elements

random_array = np.random.random((2,3))
print(random_array)

[[0.54042822 0.98261698 0.61153507]
 [0.61346668 0.74224815 0.91884824]]


In [27]:
integer_random = np.random.randint(1,5,(3,3))  # random integer between 1 - 5
print(integer_random)
type(integer_random)

[[3 2 1]
 [2 2 3]
 [4 3 2]]


numpy.ndarray

In [34]:
# transpose array

array = np.random.randint(1,10,(2,3))
print(array)

transposed_array = array.T
print(transposed_array)

[[4 8 3]
 [5 9 5]]
[[4 5]
 [8 9]
 [3 5]]


In [42]:
# reshaping array

array = np.random.random((3,4))
print(array)

reshaped_array = array.reshape(12,1)
print(reshaped_array)

[[0.9336723  0.33735373 0.6341308  0.68719586]
 [0.26344779 0.04575413 0.81062975 0.03302233]
 [0.76554746 0.55855585 0.12496545 0.41773592]]
[[0.9336723 ]
 [0.33735373]
 [0.6341308 ]
 [0.68719586]
 [0.26344779]
 [0.04575413]
 [0.81062975]
 [0.03302233]
 [0.76554746]
 [0.55855585]
 [0.12496545]
 [0.41773592]]


Numpy array slicing

Slicing -> taking elements from one index to another index

In [47]:
import numpy as np

array = np.array([8,5,4,9,6,3])
print(array[1:5])  # [start:end]

[5 4 9 6]


In [49]:
print(array)
print(array[:4])

[8 5 4 9 6 3]
[8 5 4 9]


In [50]:
print(array)
print(array[2:])

[8 5 4 9 6 3]
[4 9 6 3]


In [52]:
print(array)
print(array[1:5:2])  # [start:end:step]
print(array[::3])  # 3 step from 0 index

[8 5 4 9 6 3]
[5 9]
[8 9]


Slicing in 2D array

In [54]:
a = np.array([[2,4,8,6,5,2],[8,7,2,6,9,4]])
print(a)

[[2 4 8 6 5 2]
 [8 7 2 6 9 4]]


In [56]:
print(a[1,1:4])  # slicing rows

[7 2 6]


In [60]:
print(a[:,1:3])  # slicing column

[[4 8]
 [7 2]]
